### ISSUE TITLE
Website DNS is down

### ISSUE THREAD

**Issue by wjk** [x509online/certcentral#4]
What the title says. DNS name cannot be resolved. This was the only good way of doing peer-to-peer validation of code-signing certificates that I know of. I'm said to see its (probable) death. 😢

**Comment by wjk** [comment]
Actually… the DNS name is the _only_ thing that is down. If I go to https://x509online.azurewebsites.net/, the website loads and is AFAICT fully functional. But still, not a good sign for the health of this project.

**Comment by ridomin** [comment]
Hi @wjk 

Yes, you are right, the DNS record is not longer maintained. I've updated the READMEs and repo and orgs description to use the default azurewebsites FQDN. Let me know if there is anything else to update to close this issue.

Just for curiosity, how did you knew about this project?

**Comment by wjk** [comment]
I don't quite remember, honestly. It's been a while. I think I found it after it was featured in the "Explore repositories" sidebar of the GitHub home page. Thanks so much, and I look forward to seeing this project thrive! 😄

**Comment by ridomin** [comment]
To be honest, I'm the only maintainer and I don't expect to add any new features soon. Please let me know if you are interested to become an active collaborator. For now I'm closing this.
